# Model Evaluation
---

## Objective

In this notebook, we evaluate the performance of the baseline Linear Regression model built using the reusable machine learning pipeline.

The evaluation focuses on:

- Assessing model performance on both training and validation datasets.
- Calculating standard regression evaluation metrics.
- Comparing training and validation performance to assess generalization.
- Establishing a baseline for future comparison with regularized regression models.
---

### Step 01 : Import Libraries

In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression


from pathlib import Path
import sys

project_root = Path.cwd().parent
sys.path.append(str(project_root))

from src.pipeline import create_pipeline

### Project Root vs. Current Working Directory

Adding the project root to `sys.path` allows Python to locate **modules** (e.g., `src.pipeline`) during imports.

It **does not** affect file operations such as `pd.read_csv()`, which resolve paths relative to the **current working directory** (`Path.cwd()`) unless an absolute path is provided.

```python
project_root = Path.cwd().parent

data_path = project_root / "data" / "train.csv"
df = pd.read_csv(data_path)
```

---

### Step 02 : Load Dataset

In [2]:
df=pd.read_csv('../data/train.csv')

---

### Step 03:Train-Validation Split

In [3]:
# Separate Features and Target Variable
X = df.drop(columns=["SalePrice","Id"])
y = df["SalePrice"]

# Train-Validation Split
X_train, X_valid, y_train, y_valid = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [4]:
print(f"Training Features   : {X_train.shape}")
print(f"Validation Features : {X_valid.shape}")

print()

print(f"Training Target     : {y_train.shape}")
print(f"Validation Target   : {y_valid.shape}")

Training Features   : (1168, 79)
Validation Features : (292, 79)

Training Target     : (1168,)
Validation Target   : (292,)


---


### Step 04 : Build and Train the Baseline Pipeline

A reusable machine learning pipeline is created using the custom preprocessing transformers and a Linear Regression model.

The pipeline is trained only on the training dataset to prevent data leakage.

In [5]:
pipeline = create_pipeline(
    LinearRegression()
)

pipeline.fit(X_train, y_train)




,"steps steps: list of tuplesList of (name of step, estimator) tuples that are to be chained insequential order. To be compatible with the scikit-learn API, all stepsmust define `fit`. All non-last steps must also define `transform`. See:ref:`Combining Estimators <combining_estimators>` for more details.","[('dataset_preprocessing', ...), ('column_transformer', ...), ...]"
,"transform_input transform_input: list of str, default=NoneThe names of the :term:`metadata` parameters that should be transformed by thepipeline before passing it to the step consuming it.This enables transforming some input arguments to ``fit`` (other than ``X``)to be transformed by the steps of the pipeline up to the step which requiresthem. Requirement is defined via :ref:`metadata routing <metadata_routing>`.For instance, this can be used to pass a validation set through the pipeline.You can only set this if metadata routing is enabled, which youcan enable using ``sklearn.set_config(enable_metadata_routing=True)``... versionadded:: 1.6",None
,"memory memory: str or object with the joblib.Memory interface, default=NoneUsed to cache the fitted transformers of the pipeline. The last stepwill never be cached, even if it is a transformer. By default, nocaching is performed. If a string is given, it is the path to thecaching directory. Enabling caching triggers a clone of the transformersbefore fitting. Therefore, the transformer instance given to thepipeline cannot be inspected directly. Use the attribute ``named_steps``or ``steps`` to inspect estimators within the pipeline. Caching thetransformers is advantageous when fitting is time consuming. See:ref:`sphx_glr_auto_examples_neighbors_plot_caching_nearest_neighbors.py`for an example on how to enable caching.",None
,"verbose verbose: bool, default=FalseIf True, the time elapsed while fitting each step will be printed as itis completed.",False
,"steps steps: list of tuplesList of (name of step, estimator) tuples that are to be chained insequential order. To be compatible with the scikit-learn API, all stepsmust define `fit`. All non-last steps must also define `transform`. See:ref:`Combining Estimators <combining_estimators>` for more details.","[('numerical_missing_values', ...), ('categorical_missing_values', ...), ...]"
,"transform_input transform_input: list of str, default=NoneThe names of the :term:`metadata` parameters that should be transformed by thepipeline before passing it to the step consuming it.This enables transforming some input arguments to ``fit`` (other than ``X``)to be transformed by the steps of the pipeline up to the step which requiresthem. Requirement is defined via :ref:`metadata routing <metadata_routing>`.For instance, this can be used to pass a validation set through the pipeline.You can only set this if metadata routing is enabled, which youcan enable using ``sklearn.set_config(enable_metadata_routing=True)``... versionadded:: 1.6",None
,"memory memory: str or object with the joblib.Memory interface, default=NoneUsed to cache the fitted transformers of the pipeline. The last stepwill never be cached, even if it is a transformer. By default, nocaching is performed. If a string is given, it is the path to thecaching directory. Enabling caching triggers a clone of the transformersbefore fitting. Therefore, the transformer instance given to thepipeline cannot be inspected directly. Use the attribute ``named_steps``or ``steps`` to inspect estimators within the pipeline. Caching thetransformers is advantageous when fitting is time consuming. See:ref:`sphx_glr_auto_examples_neighbors_plot_caching_nearest_neighbors.py`for an example on how to enable caching.",None
,"verbose verbose: bool, default=FalseIf True, the time elapsed while fitting each step will be printed as itis completed.",False
Name,Type,Value
lotfrontage_median_,"Series[float64](25,)",Neighborhood ...dtype: float64
Name,Type,Value


---

### Step 05 : Generate Predictions

Predictions are generated for both the training and validation datasets.

Evaluating both datasets helps assess the model's ability to generalize to unseen data.

In [6]:
y_train_pred = pipeline.predict(X_train)

y_valid_pred = pipeline.predict(X_valid)

---

### Step 06: Baseline Model Evaluation

In this step, the baseline **Linear Regression** model is evaluated on both the training and validation datasets.

The objective is to establish a benchmark by measuring the model's predictive performance using multiple regression evaluation metrics. This baseline will serve as a reference for comparing more advanced models such as Ridge Regression, Lasso Regression, and ElasticNet in subsequent steps.

The evaluation process includes:

- Generating predictions on the training and validation datasets.
- Computing regression evaluation metrics.
- Comparing training and validation performance.
- Interpreting the model's ability to generalize to unseen data.
---

## Evaluation Metrics

To evaluate the performance of the regression model, the following metrics are used. Each metric provides a different perspective on the model's predictive performance, so they should be interpreted together rather than individually.

---

### 1. Mean Absolute Error (MAE)

#### Definition

Mean Absolute Error (MAE) measures the average absolute difference between the actual and predicted target values.

It considers only the magnitude of prediction errors, treating overestimation and underestimation equally.

A lower MAE indicates better model performance.

#### Formula

$$
MAE=\frac{1}{n}\sum_{i=1}^{n}|y_i-\hat{y}_i|
$$

#### Advantages

- Easy to interpret.
- Expressed in the same unit as the target variable.
- Less sensitive to outliers than MSE and RMSE.

#### Limitation

MAE does not place additional emphasis on large prediction errors. As a result, it may not be suitable for applications where large errors are significantly more costly than small ones.

---

### 2. Mean Squared Error (MSE)

#### Definition

Mean Squared Error (MSE) measures the average squared difference between the actual and predicted target values.

By squaring prediction errors before averaging, MSE penalizes large errors more heavily than small ones, making it more sensitive to outliers.

A lower MSE indicates better model performance.

#### Formula

$$
MSE=\frac{1}{n}\sum_{i=1}^{n}(y_i-\hat{y}_i)^2
$$

#### Advantages

- Penalizes large prediction errors more heavily.
- Differentiable, making it suitable as an optimization objective for many machine learning algorithms.

#### Limitation

Since prediction errors are squared, large errors receive disproportionately higher penalties. As a result, MSE is highly sensitive to outliers.

---

### 3. Root Mean Squared Error (RMSE)

#### Definition

Root Mean Squared Error (RMSE) is the square root of the Mean Squared Error (MSE).

It expresses the prediction error in the same unit as the target variable while still penalizing large prediction errors more heavily.

A lower RMSE indicates better model performance.

#### Formula

$$
RMSE=\sqrt{\frac{1}{n}\sum_{i=1}^{n}(y_i-\hat{y}_i)^2}
$$

#### Advantages

- Expressed in the same unit as the target variable.
- Easier to interpret than MSE.
- Penalizes large prediction errors more heavily than MAE.

#### Limitation

Since RMSE is based on squared errors, it remains sensitive to outliers. Large prediction errors have a greater influence on the metric than small errors.

---

### 4. R² Score (Coefficient of Determination)

#### Definition

The R² score measures the proportion of the variance in the target variable that is explained by the regression model.

It compares the model's predictions against a baseline model that always predicts the mean of the target variable.

An R² score closer to **1** indicates that the model explains a larger proportion of the variability in the target.

#### Formula

$$
R^2 = 1-\frac{SS_{res}}{SS_{tot}}
$$

where,

$$
SS_{res}=\sum_{i=1}^{n}(y_i-\hat{y}_i)^2
$$

$$
SS_{tot}=\sum_{i=1}^{n}(y_i-\bar{y})^2
$$

#### Advantages

- Unitless metric.
- Easy to compare different regression models.
- Indicates how much variance in the target is explained by the model.

#### Limitation

R² generally increases or remains unchanged when additional features are added, even if they do not improve the model's predictive ability. Therefore, it may overestimate the performance of more complex models.

---

### 5. Adjusted R² Score

#### Definition

Adjusted R² is a modified version of the R² score that accounts for the number of predictor variables in the model.

Unlike R², Adjusted R² increases only when newly added features provide a meaningful improvement in the model's performance. It may decrease if additional features do not contribute useful information.

As a result, Adjusted R² is a more reliable metric for comparing regression models with different numbers of predictors.

#### Formula

$$
Adjusted\ R^2=
1-(1-R^2)\times\frac{n-1}{n-p-1}
$$

where,

- **n** = Number of observations
- **p** = Number of predictor variables

#### Advantages

- Penalizes unnecessary predictor variables.
- Better suited for comparing regression models with different numbers of features.
- Encourages simpler models without sacrificing predictive performance.

#### Limitation



Adjusted R² accounts for model complexity by penalizing the inclusion of additional predictors during model fitting. Since this adjustment is based on the data used to estimate the model parameters, it does not directly measure how well the model generalizes to unseen data. Therefore, Adjusted R² is primarily reported for the training data, while model performance on validation or test datasets is better assessed using prediction-based metrics such as MAE, RMSE, and R².

---



### Step 06.1: Import Evaluation Metrics

In [7]:
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    root_mean_squared_error,
    r2_score,
)

---

### Step 06.2: Evaluate the Baseline Model Using the Reusable Evaluation Function

To ensure consistency and avoid code duplication, a reusable evaluation function is used to compute the regression metrics for the baseline model.

The function calculates the following metrics:

- Mean Absolute Error (MAE)
- Mean Squared Error (MSE)
- Root Mean Squared Error (RMSE)
- R² Score
- Adjusted R² Score

The same function is applied to both the training and validation predictions, ensuring a consistent evaluation process across different regression models. This modular approach improves code reusability, maintainability, and simplifies future model comparisons.

Since the model is trained on the transformed feature space, the number of predictor variables is obtained from the fitted preprocessing pipeline and used to calculate the Adjusted R² score.


In [8]:
#Import evaluation fun
from src.evaluation import evaluate_regression_model
pd.options.display.float_format = "{:.4f}".format

# Number of features after preprocessing
n_features = len(
    pipeline.named_steps["column_transformer"]
    .get_feature_names_out()
)

# Training metrics
train_metrics = evaluate_regression_model(
    y_true=y_train,
    y_pred=y_train_pred,
    n_features=n_features,
    adjusted_r2=True,
)
# Validation metrics
validation_metrics = evaluate_regression_model(
    y_true=y_valid,
    y_pred=y_valid_pred,
)

---

### Step 06.3: Summarize & Interprete Evaluation Results

The evaluation metrics for the training and validation datasets are consolidated into a single summary table.

Presenting the metrics in a tabular format enables a clear comparison of model performance across datasets and provides a baseline for evaluating and comparing future regression models.

In [9]:
baseline_model_evaluation_summary = pd.DataFrame(
    {
        "Training": train_metrics,
        "Validation": validation_metrics,
    }
).round(4)

baseline_model_evaluation_summary

,Training,Validation
MAE,12122.9814,21102.1314
MSE,357571606.3302,4272188098.3658
RMSE,18909.5639,65361.9775
R²,0.9401,0.4430
Adjusted R²,0.9191,NaN


### Interpretation

The baseline Linear Regression model achieves strong performance on the training dataset, with an **R² score of 0.9401**, indicating that it explains approximately **94.01%** of the variance in the training data. The relatively low MAE and RMSE further suggest that the model fits the training data well.

However, the model's performance deteriorates on the validation dataset. The validation **R² score decreases to 0.4430**, while both the MAE and RMSE increase substantially. This indicates that the model is less effective at predicting unseen data.

The noticeable gap between the training and validation metrics suggests that the baseline model is experiencing **overfitting (high variance)**. Although it captures the patterns present in the training data effectively, it does not generalize well to new observations.

Overall, the Linear Regression model provides a useful baseline for comparison with more advanced regression models. In the subsequent steps, regularized regression models such as Ridge, Lasso, and ElasticNet will be evaluated to improve generalization performance and reduce overfitting.

----